language: ruby
sudo: false
cache:
  bundler: true
notifications:
  email:
  - diego.domingues16@gmail.com, rogerio.alcantara@gmail.com
  slack:
    secure: IPOo1MyOQqAHAemn+Y0KwchRn0858HiZit/ixrLGKhEDmyZtHWK2FIqJzKuaOYRqKYnG5hlml/dIE2R+Sbe5fPTke1xzPg1V1LSFk+55y3ypqHGKU43POnipXc7HF7w6v2INktodOwrTDucC7ABD7MXeOSJ7QJvv+aRvK8RmL56RC4uAJiPs6EqxRGYR8LymH6AOmnDiioe1pywgp47T/7X2svLBl0D98CYrJ9SiKxK/VyJlx2dZhlhaoDQHkYk0khYzxlAt3TevTGzsaIIlbVBOLsBHni4iq8n1HSANXaVrLBGVqYRCGBJBmLDWjGdsHW7YhT7XUoeIW/c4uy02pmPKfIxJyRj5Gr1kxhMkpJvS8EDyssFo9n7I/MUrGOwa+coaucz7GrO3RcmnNB5WdBEtTKP9zJo0FIkkBtOMmZdMKxlXUgwz1tBsYj7ovV3939n51yEK6w68w2Vg1pBAM3J4RYRudEO4+3LhJZ6b6w+XQgXf+ybYvN+lrAgleQobbwRopH7Cqn5Ej0r4WrONpZrxvtsQ1BGojPPz7UpE3ZZab7hDUMgLNOTiRgw7GK6oqqsC8EGlnfpfGtUSjuneawmTRozIk7DOIMek3mCY36+rJGNqs21kZf+KBIDT9sNUTsgpsG/XKOtHhw5cxEXYE/7qdIq9X5NP9bcOuqv4/u8=
branches:
  only:
  - master
